version: '3'
networks:
  todo-app-network:
volumes:
  mariadb_data:
  redis_data:
services:
  # MariaDB
  db:
    image: mariadb:latest
    container_name: 'mariadb'
    networks:
      - todo-app-network
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - '3306:3306'
  # Redis
  redis:
    image: redis:latest
    container_name: redis
    networks:
      - todo-app-network
    environment:
      REDIS_URL: ${REDIS_URL}
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    networks:
      - todo-app-network
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq/
  #Application
  todo-app:
    image: sergiodot/todo-app:1.0
    container_name: todo-app
    networks:
      - todo-app-network
    environment:
      SERVER_PORT: ${SERVER_PORT}
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      JWT_ACCESS_TIME: ${JWT_ACCESS_TIME}
      JWT_REFRESH_TIME: ${JWT_REFRESH_TIME}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      REDIS_URL: ${REDIS_URL}
      RABBITMQ_URL: ${RABBITMQ_URL}
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    depends_on:
      - db
      - rabbitmq
      - redis
